### ISSUE TITLE
Not working correctly starting with Docker 17.04.0-ce

### ISSUE THREAD

**Issue by pitkley** [irsl/dfwfw#13]
Docker 17.04.0-ce introduced a breaking change in that the `/networks` endpoint no longer returns the containers attached to the networks but rather an empty dict (`{}`). You now have to request the containers for every network specifically on the `/networks/<network-name>` endpoint.

See:

* this related issue: https://github.com/moby/moby/issues/32686
* this code-comment: [network_routes.go#L66-L69](https://github.com/moby/moby/blob/7936a962dc5f0f97fa2195c9497bc6e21e13fc2e/api/server/router/network/network_routes.go#L66-L69)

I am fairly certain that this change is hitting DFWFW, since I had no success of getting container-related rules generated under 17.04.0-ce, but experienced no isssues under 17.03.1-ce.

Two solutions (rather one solution and one work-around) I can think of:

* Request the containers for every network specifically, conforming to the new expected behaviour.

* Specify the API-version to use as `1.27` or below in [dfwfw.pl#L118](https://github.com/irsl/dfwfw/blob/614f6dcfc4cf1abfb29953e6c159493513fb1920/dfwfw/dfwfw.pl#L118) similar to what is already done in [WebService::Docker::Info](https://github.com/irsl/WebServiceDocker/blob/master/lib/WebService/Docker/Info.pm#L26).

    This might have a change of breaking in the future, I am not sure how the Docker developers handle a deprecation like this.

I have not tried either of the possibilities, especially since I'm not really firm with Perl.

**Comment by irsl** [comment]
The latest commit in WebService::Docker::Info addresses the API changes in Docker. The line in Dfwfw you referenced ([dfwfw.pl#L118](https://github.com/irsl/dfwfw/blob/614f6dcfc4cf1abfb29953e6c159493513fb1920/dfwfw/dfwfw.pl#L118)) is an WebService::Docker::API instance that is responsible for reading the event stream only; the network-container info is retrieved somewhere else (through WebService::Docker::Info, via API version 1.12).

I'm on 17.04.0-ce now and the tool is working for me as expected. Did you install the Dfwfw image from the Docker hub? For some reason, the build was not triggered there automatically, offering a year old version. I just rebuilt there manually.

**Comment by pitkley** [comment]
I came across the setting you mentioned in `WebService::Docker::Info` and was surprised that I was still experiencing issues, to which I concluded that the `::API` reference was the relevant one -- which apparently it is not.

I was using the image from Docker hub, so that was in fact the issue. With the latest version pulled it is working without issues again. Thanks for the response! 👍
