### ISSUE TITLE
dfwfw startup fails with err

### ISSUE THREAD

**Issue by beeyeas** [irsl/dfwfw#5]
Could not start the dfwfw container when i try 

docker run \
  --name=dfwfw -d \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /path/to/your/dfwfw.conf:/etc/dfwfw/dfwfw.conf \
  --net=host \
  --cap-add=NET_ADMIN \
  dfwfw

Can't locate WebService/Docker/API.pm in @INC (you may need to install the WebService::Docker::API module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl . /opt/dfwfw /opt/dfwfw/WebServiceDocker /opt/dfwfw/ConfigHostsFile /opt/dfwfw/PreJSON) at /opt/dfwfw/dfwfw.pl line 14.
BEGIN failed--compilation aborted at /opt/dfwfw/dfwfw.pl line 14.

**Comment by rlanore** [comment]
I think, you need to init git submodule

or

git clone --recursive git://github.com/foo/bar.git

**Comment by irsl** [comment]
I believe you did not install the git submodules hence Perl is unable to locate those dependencies.
I just updated the installation chapter of the documentation; recommended installation method is added:

```
docker build -t dfwfw https://github.com/irsl/dfwfw.git
```

**Comment by irsl** [comment]
I close this ticket now. Open a new one if the issue persists.
