### ISSUE TITLE
Enabling port forwarding between two containers

### ISSUE THREAD

**Issue by vrastogi** [irsl/dfwfw#8]
I want to forward a port from one container to another. I did something like this:

```
   "container_dnat": {
       "rules": [
          { 
             "filter": "-p tcp --dport 5001",
             "src_network":   "bridge",
             "src_container": "src",
             "dst_network":   "bridge",
             "dst_container": "dst",
             "expose_port": "5001/tcp" 
          }
       ]
   }
```

I have a server listening on dst:5001 and I want to connect at src:5001 from inside src. The above does not work. What changes should I do to get it working?

Moreover, I see these rules generated by dfwfw:
-A DFWFW_PREROUTING -i docker0 -p tcp -m tcp --dport 5001 -j DNAT --to-destination 172.17.0.3:5001
-A DFWFW_FORWARD -s 172.17.0.2/32 -d 172.17.0.3/32 -i docker0 -o docker0 -p tcp -m tcp --dport 5001 -j ACCEPT

What am I missing?

**Comment by bigfoot90** [comment]
**SOLVED**
I've had run docker engine widthout the iptable integration.
*To do that on Ubuntu systems I've ran this command from terminal:*
```
mkdir /etc/systemd/system/docker.service.d
cat << EOF > /etc/systemd/system/docker.service.d/noiptables.conf
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// --iptables=false
EOF
systemctl daemon-reload
```

I've also update my config:
```
   "wider_world_to_container": {
       "rules": [
          {
             "network": "bridge",
             "external_network_interface": "tap0",
             "dst_container": "nginx",
             "expose_port": 8080
          }
       ]
   }
```

**Comment by vrastogi** [comment]
@bigfoot90 Your config seems to route the requests from anywhere to the host (tap0) at port 8080 to the nginx container. What I need is port forwarding between containers. Please see the OP.

**Comment by bigfoot90** [comment]
@vrastogi I wrote on wrong issue. Sorry.
Have you seen the [container to container](https://github.com/irsl/dfwfw/blob/master/EXAMPLES.md#container-to-container-rules) section?

**Comment by vrastogi** [comment]
@bigfoot90 The container_to_container section cannot perform address
translation as far as I can tell.

**Comment by irsl** [comment]
In your configuration the packets actually never leave the network stack of the container, as both the source and the destination IPs are the same (src).
You can circumvent this by injecting an additional DNAT rule into the container, something like this:

```
  "container_internals": {
     "rules": [
          {
              "container": "src",
              "table": "nat",
              "rules": "-A OUTPUT -p tcp --dport 5001 -j DNAT --to-destination 1.1.1.1"
          }
     ]
  }
```

Then you should be able to connect to src:5001 from src and the packets will be routed to dst:5001.

(Note the container_internal rule above will actually append this iptables rule every time dfwfw processes an event, you should consider flushing, which in turn would - unfortunately - remove rules added by Docker for its internal name resolution. This is a known limitation currently.)

Please also upgrade the application, the iptables rule generated by container_dnat for allowing the communication between two containers (the one other than the DNAT), was chained after the default rule of container_container, so in case default was REJECT, the communication was actually not allowed.

This is something which will most probably have some backward-incompatible changes in the future.

**Comment by vrastogi** [comment]
Thanks for the detailed response. Not knowing something like this could be done with `container_internals`, I was using iptables directly.

Closing this issue for now.
